app/urls.py
from django.urls import path
from . import views

app_name = 'web'
urlpatterns = [
    path('home/', views.main, name='main'),
    path('cart/', views.ShopCart.as_view(), name='shop-cart'),
]

login/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.UserSignUp.as_view(), name='signup'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("app.urls")),
    path('view/', include("login.urls")),
    path('admin/', include("customadmin.urls")),
    path('django-admin/', admin.site.urls),
]

app/templates/app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
{% block head %}
{% endblock %}
<body class="animsition">
	{% block header %}
	<header>
		{% include 'app/header.html' %}
	</header>
	{% endblock %}

	<!-- Cart -->
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>

			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full" data-product-card-list="list">
					<div style="font-weight: bold">No product on your cart</div>
				</ul>

				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40" data-product-card-allprice="total" style="font-weight: bold">
						Total: $0
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="{% url 'web:shop-cart' %}" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Slider -->
	{% block slider %}
	{% endblock %}

	<!-- Banner -->
	{% block banner %}
	{% endblock %}

	<!-- Product -->
	{% block product %}
	{% endblock %}

	<!-- breadcrumb -->
	{% block breadcrumb %}
	{% endblock %}

	<!-- Shoping Cart -->
	{% block shopcart %}
	{% endblock %}

    {% include 'app/footer.html' %}

	<!-- Back to top -->
	<div class="btn-back-to-top" id="myBtn">
		<span class="symbol-btn-back-to-top">
			<i class="zmdi zmdi-chevron-up"></i>
		</span>
	</div>

	<!-- Modal1 -->
	{% block modal %}
	{% endblock %}

	{% block script %}
	{% endblock %}

</body>
</html>

app/templates/app/footer.html
{% load static %}
<footer class="bg3 p-t-75 p-b-32">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-3 p-b-50">
                <h4 class="stext-301 cl0 p-b-30">
                    Categories
                </h4>

                <ul>
                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Women
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Men
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Shoes
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Watches
                        </a>
                    </li>
                </ul>
            </div>

            <div class="col-sm-6 col-lg-3 p-b-50">
                <h4 class="stext-301 cl0 p-b-30">
                    Help
                </h4>

                <ul>
                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Track Order
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Returns
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            Shipping
                        </a>
                    </li>

                    <li class="p-b-10">
                        <a href="#" class="stext-107 cl7 hov-cl1 trans-04">
                            FAQs
                        </a>
                    </li>
                </ul>
            </div>

            <div class="col-sm-6 col-lg-3 p-b-50">
                <h4 class="stext-301 cl0 p-b-30">
                    GET IN TOUCH
                </h4>

                <p class="stext-107 cl7 size-201">
                    Any questions? Let us know in store at 8th floor, 379 Hudson St, New York, NY 10018 or call us on
                    (+1) 96 716 6879
                </p>

                <div class="p-t-27">
                    <a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
                        <i class="fa fa-facebook"></i>
                    </a>

                    <a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
                        <i class="fa fa-instagram"></i>
                    </a>

                    <a href="#" class="fs-18 cl7 hov-cl1 trans-04 m-r-16">
                        <i class="fa fa-pinterest-p"></i>
                    </a>
                </div>
            </div>

            <div class="col-sm-6 col-lg-3 p-b-50">
                <h4 class="stext-301 cl0 p-b-30">
                    Newsletter
                </h4>

                <form>
                    <div class="wrap-input1 w-full p-b-4">
                        <input class="input1 bg-none plh1 stext-107 cl7" type="text" name="email"
                               placeholder="email@example.com">
                        <div class="focus-input1 trans-04"></div>
                    </div>

                    <div class="p-t-18">
                        <button class="flex-c-m stext-101 cl0 size-103 bg1 bor1 hov-btn2 p-lr-15 trans-04">
                            Subscribe
                        </button>
                    </div>
                </form>
            </div>
        </div>

        <div class="p-t-40">
            <div class="flex-c-m flex-w p-b-18">
                <a href="#" class="m-all-1">
                    <img src="images/icons/icon-pay-01.png" alt="ICON-PAY">
                </a>

                <a href="#" class="m-all-1">
                    <img src="images/icons/icon-pay-02.png" alt="ICON-PAY">
                </a>

                <a href="#" class="m-all-1">
                    <img src="images/icons/icon-pay-03.png" alt="ICON-PAY">
                </a>

                <a href="#" class="m-all-1">
                    <img src="images/icons/icon-pay-04.png" alt="ICON-PAY">
                </a>

                <a href="#" class="m-all-1">
                    <img src="images/icons/icon-pay-05.png" alt="ICON-PAY">
                </a>
            </div>

            <p class="stext-107 cl6 txt-center">
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                All rights reserved | Made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
                    href="https://colorlib.com" target="_blank">Colorlib</a> &amp; distributed by <a
                    href="https://themewagon.com" target="_blank">ThemeWagon</a>
                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->

            </p>
        </div>
    </div>
</footer>

app/templates/app/header.html
{% load static %}
<!-- Header desktop -->
<div class="container-menu-desktop">
    <!-- Topbar -->
    <div class="top-bar">
        <div class="content-topbar flex-sb-m h-full container">
            <div class="left-top-bar">
                Free shipping for standard order over $100
            </div>

            <div class="right-top-bar flex-w h-full">
                {% if request.user.is_authenticated %}
                    <a href="" class="flex-c-m trans-04 p-lr-25">
                        Xin chào, {{ request.user.first_name }}
                    </a>
                    <a href="{% url 'login:logout' %}" class="flex-c-m trans-04 p-lr-25">
                        Thoát
                    </a>
                    <input value="{{ request.user.username }}" type="hidden" data-user-check-login="check">
                {% else %}
                    <a href="{% url 'login:login' %}" class="flex-c-m trans-04 p-lr-25">
                        Đăng nhập
                    </a>
                    <input value="" type="hidden" data-user-check-login="check">
                {% endif %}

            </div>
        </div>
    </div>

    <div class="wrap-menu-desktop">
        <nav class="limiter-menu-desktop container">

            <!-- Logo desktop -->
            <a href="#" class="logo">
                <img src="{% static 'shop/images/icons/logo-01.png' %}" alt="IMG-LOGO">
            </a>

            <!-- Menu desktop -->
            <div class="menu-desktop">
                <ul class="main-menu">
                    <li class="active-menu">
                        <a href="{% url 'web:main' %}">Home</a>
<!--                        <ul class="sub-menu">-->
<!--                            <li><a href="index.html">Homepage 1</a></li>-->
<!--                            <li><a href="home-02.html">Homepage 2</a></li>-->
<!--                            <li><a href="home-03.html">Homepage 3</a></li>-->
<!--                        </ul>-->
<!--                    </li>-->

                    <li>
                        <a href="product.html">Shop</a>
                    </li>

                    <li class="label1" data-label1="hot">
                        <a href="shoping-cart.html">Features</a>
                    </li>

                    <li>
                        <a href="blog.html">Blog</a>
                    </li>

                    <li>
                        <a href="about.html">About</a>
                    </li>

                    <li>
                        <a href="contact.html">Contact</a>
                    </li>
                </ul>
            </div>

            <!-- Icon header -->
            <div class="wrap-icon-header flex-w flex-r-m">
                <div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 js-show-modal-search">
                    <i class="zmdi zmdi-search"></i>
                </div>

                <div class="icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti js-show-cart"
                     data-notify="0" data-notify-number="notification-cart">
                    <i class="zmdi zmdi-shopping-cart"></i>
                </div>

                <a href="#" class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-l-22 p-r-11 icon-header-noti"
                   data-notify="0">
                    <i class="zmdi zmdi-favorite-outline"></i>
                </a>
            </div>
        </nav>
    </div>
</div>

<!-- Header Mobile -->
<div class="wrap-header-mobile">
    <!-- Logo moblie -->
    <div class="logo-mobile">
        <a href="index.html"><img src="images/icons/logo-01.png" alt="IMG-LOGO"></a>
    </div>

    <!-- Icon header -->
    <div class="wrap-icon-header flex-w flex-r-m m-r-15">
        <div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 js-show-modal-search">
            <i class="zmdi zmdi-search"></i>
        </div>

        <div class="icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti js-show-cart"
             data-notify="0" data-notify-number="notification-cart">
            <i class="zmdi zmdi-shopping-cart"></i>
        </div>

        <a href="#" class="dis-block icon-header-item cl2 hov-cl1 trans-04 p-r-11 p-l-10 icon-header-noti"
           data-notify="0">
            <i class="zmdi zmdi-favorite-outline"></i>
        </a>
    </div>

    <!-- Button show menu -->
    <div class="btn-show-menu-mobile hamburger hamburger--squeeze">
            <span class="hamburger-box">
                <span class="hamburger-inner"></span>
            </span>
    </div>
</div>


<!-- Menu Mobile -->
<div class="menu-mobile">
    <ul class="topbar-mobile">
        <li>
            <div class="left-top-bar">
                Free shipping for standard order over $100
            </div>
        </li>

        <li>
            <div class="right-top-bar flex-w h-full">
                {% if request.user.is_authenticated %}
                    <a href="" class="flex-c-m trans-04 p-lr-25">
                        Xin chào, {{ request.user.first_name }}
                    </a>
                    <a href="{% url 'login:logout' %}" class="flex-c-m trans-04 p-lr-25">
                        Thoát
                    </a>
                    <input value="{{ request.user.username }}" type="hidden" data-user-check-login="check">
                {% else %}
                    <a href="{% url 'login:login' %}" class="flex-c-m trans-04 p-lr-25">
                        Đăng nhập
                    </a>
                    <input value="" type="hidden" data-user-check-login="check">
                {% endif %}
            </div>
        </li>
    </ul>

    <ul class="main-menu-m">
        <li>
            <a href="{% url 'web:main' %}">Home</a>
<!--            <ul class="sub-menu-m">-->
<!--                <li><a href="index.html">Homepage 1</a></li>-->
<!--                <li><a href="home-02.html">Homepage 2</a></li>-->
<!--                <li><a href="home-03.html">Homepage 3</a></li>-->
<!--            </ul>-->
<!--            <span class="arrow-main-menu-m">-->
<!--                    <i class="fa fa-angle-right" aria-hidden="true"></i>-->
<!--                </span>-->
        </li>

        <li>
            <a href="product.html">Shop</a>
        </li>

        <li>
            <a href="shoping-cart.html" class="label1 rs1" data-label1="hot">Features</a>
        </li>

        <li>
            <a href="blog.html">Blog</a>
        </li>

        <li>
            <a href="about.html">About</a>
        </li>

        <li>
            <a href="contact.html">Contact</a>
        </li>
    </ul>
</div>

<!-- Modal Search -->
<div class="modal-search-header flex-c-m trans-04 js-hide-modal-search">
    <div class="container-search-header">
        <button class="flex-c-m btn-hide-modal-search trans-04 js-hide-modal-search">
            <img src="images/icons/icon-close2.png" alt="CLOSE">
        </button>

        <form class="wrap-search-header flex-w p-l-15">
            <button class="flex-c-m trans-04">
                <i class="zmdi zmdi-search"></i>
            </button>
            <input class="plh3" type="text" name="search" placeholder="Search...">
        </form>
    </div>
</div>

app/templates/app/shop-cart.html
{% extends 'app/base.html' %}
{% load static %}
{% block head %}
<head>
	<title>Shop cart</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="icon" type="image/png" href="{% static 'shop/images/icons/favicon.png' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'shop/vendor/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/fonts/iconic/css/material-design-iconic-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/fonts/linearicons-v1.0.0/icon-font.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/vendor/animate/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/vendor/css-hamburgers/hamburgers.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/vendor/animsition/css/animsition.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/vendor/select2/select2.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/vendor/perfect-scrollbar/perfect-scrollbar.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/css/util.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'shop/css/main.css' %}">
	<link href="{% static 'assets/plugins/global/plugins.bundle.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'assets/css/style.bundle.css' %}" rel="stylesheet" type="text/css"/>
<!--	<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap">-->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter:300,400,500,600,700"/>
    <style>
        body, html {
            font-family: Inter, Helvetica, "sans-serif";
        }
    </style>
</head>
{% endblock %}

{% block header %}
	<header class="header-v4">
		{% include 'app/header.html' %}
	</header>
{% endblock %}

{% block breadcrumb %}
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">
			<a href="index.html" class="stext-109 cl8 hov-cl1 trans-04">
				Home
				<i class="fa fa-angle-right m-l-9 m-r-10" aria-hidden="true"></i>
			</a>

			<span class="stext-109 cl4">
				Shoping Cart
			</span>
		</div>
	</div>
{% endblock %}

{% block shopcart %}
	<form class="bg0 p-t-75 p-b-85" id="form-order-send">
		<div class="container">
			<div class="row">
				<div class="col-lg-10 col-xl-7 m-lr-auto m-b-50" >
					<div class="m-l-25 m-r--38 m-lr-0-xl">
						<div class="wrap-table-shopping-cart" >
							<table class="table-shopping-cart" id="table-shop-cart">
								<thead>
									<tr class="table_head">
									<th class="column-1">Product</th>
									<th class="column-2"></th>
									<th class="column-3">Price</th>
									<th class="column-4">Quantity</th>
									<th class="column-5">Total</th>
								</tr>
								</thead>
								<tbody id="tbody-shop-cart">

								</tbody>

							</table>
						</div>

						<div class="flex-w flex-sb-m bor15 p-t-18 p-b-15 p-lr-40 p-lr-15-sm">
							<div class="flex-w flex-m m-r-20 m-tb-5">
								<input class="stext-104 cl2 plh4 size-117 bor13 p-lr-20 m-r-10 m-tb-5" type="text" name="coupon" placeholder="Coupon Code">

								<div class="flex-c-m stext-101 cl2 size-118 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-5">
									Apply coupon
								</div>
							</div>

							<div class="flex-c-m stext-101 cl2 size-119 bg8 bor13 hov-btn3 p-lr-15 trans-04 pointer m-tb-10" id="update-shop-cart">
								Update Cart
							</div>
						</div>
					</div>
				</div>

				<div class="col-sm-10 col-lg-7 col-xl-5 m-lr-auto m-b-50">
					<div class="bor10 p-lr-40 p-t-30 p-b-40 m-l-63 m-r-40 m-lr-0-xl p-lr-15-sm">
						<h4 class="mtext-109 cl2 p-b-30">
							Cart Totals
						</h4>

						<div class="flex-w flex-t bor12 p-b-13">
							<div class="size-208">
								<span class="stext-110 cl2">
									Subtotal:
								</span>
							</div>

							<div class="size-209">
								<span class="mtext-110 cl2" id="subtotal">
									0
								</span>
							</div>
						</div>

						<div class="flex-w flex-t bor12 p-t-15 p-b-30">
							<span class="stext-110 cl2">
								Your information
							</span>
							<div class="">
								<p class="stext-111 cl6 p-t-2">
									Filling out your information helps us easily confirm your application
								</p>
								<div class="p-t-15">
									<span class="stext-112 cl8">
										Fill your infor
									</span>
									<div class="fv-row">
										<div class="bor8 bg0 m-b-12">
											<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="phone" placeholder="Phone Number" data-product-form-order="phone">
										</div>
									</div>
									<div class="fv-row">
										<div class="bor8 bg0 m-b-12">
											<input class="stext-111 cl8 plh3 size-111 p-lr-15" type="text" name="CustomerName" placeholder="Your Full Name" data-product-form-order="name">
										</div>
									</div>
								</div>
							</div>

						</div>

						<div class="flex-w flex-t p-t-27 p-b-33">
							<div class="size-208">
								<span class="mtext-101 cl2">
									Total:
								</span>
							</div>

							<div class="size-209 p-t-1">
								<span class="mtext-110 cl2" id="totalFullProduct">
									0
								</span>
							</div>
						</div>
						{% csrf_token %}
						{% if request.user.is_authenticated %}
							<button class="flex-c-m stext-101 cl0 size-116 bg3 bor14 hov-btn3 p-lr-15 trans-04 pointer" id="send-order">
								Proceed to Checkout
							</button>
						{% endif %}
					</div>
				</div>
			</div>
		</div>
	</form>
{% endblock %}

{% block script %}
<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
<script src="{% static 'shop/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'shop/vendor/animsition/js/animsition.min.js' %}"></script>
<script src="{% static 'shop/vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'shop/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'shop/vendor/select2/select2.min.js' %}"></script>
<script src="{% static 'shop/vendor/sweetalert/sweetalert.min.js' %}"></script>
<script>
	$(".js-select3").each(function(){
		$(this).select2({
			minimumResultsForSearch: 20,
			dropdownParent: $(this).next('.dropDownSelect2')
		});
	})
</script>
<script src="{% static 'shop/vendor/MagnificPopup/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'shop/vendor/perfect-scrollbar/perfect-scrollbar.min.js' %}"></script>
<script>
	$('.js-pscroll').each(function(){
		$(this).css('position','relative');
		$(this).css('overflow','hidden');
		var ps = new PerfectScrollbar(this, {
			wheelSpeed: 1,
			scrollingThreshold: 1000,
			wheelPropagation: false,
		});

		$(window).on('resize', function(){
			ps.update();
		})
	});
</script>
<script src="{% static 'shop/js/cart.js' %}"></script>
<script src="{% static 'shop/js/shop-cart.js' %}"></script>
<script src="{% static 'shop/js/main.js' %}"></script>
{% endblock %}